name: CD process to deploy frontend project

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.X'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'coverage[toml]' pytest pytest-cov juniper
          pip install -r requirements/prod.txt
      - name: Run Unit Tests
        run: |
           python -m pytest src/tests
      - name: Generate coverage
        run: |
          python -m pytest --cache-clear --cov-config=.coveragerc --cov=src/ src/tests/*
      - name: Check threshold of coverage
        run: |
          coverage report -m --fail-under=100
      - name: Build lambdas
        run: |
          juni build
      - name: Listing lambdas
        run: |
          ls dist
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd infrastructure
          terraform init -backend-config="access_key=$TF_VAR_aws_access_key_id" -backend-config="secret_key=$TF_VAR_aws_secret_access_key"
      - name: Terraform Validate
        id: validate
        run: |
          cd infrastructure
          terraform validate -no-color
      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          cd infrastructure
          terraform plan -no-color
        continue-on-error: true
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Terraform Apply
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          cd infrastructure
          terraform apply -auto-approve